TaskManager/Controllers/ProjectManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskManager.Models;
using Microsoft.AspNet.Identity;
using System.Data;
using System.Data.Entity.Core.Common.CommandTrees.ExpressionBuilder;
using System.Web.Script.Serialization;
using System.Diagnostics;

namespace TaskManager.Controllers
{
    public class ProjectManagerController : Controller
    {
        // GET: ProjectManager
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                ViewBag.username = Dao.Account.getUsername(User.Identity.GetUserId());
            }

            //ViewBag.projects = Dao.Projects.getAllProjects();
            return View();
        }
        public ActionResult Users(string user, string project, string type)
        {
            if (User.Identity.IsAuthenticated)
            {
                ViewBag.username = Dao.Account.getUsername(User.Identity.GetUserId());
            }


            //shows all project for  user.
            if (project == null && user != null)
            {
                if (User.Identity.IsAuthenticated)
                {
                    string username = Dao.Account.getUsername(User.Identity.GetUserId());
                    //if you own the user page you can see the projects.
                    if (username == user)
                    {

                        if (Request["filter"] == null || Request["filter"] == "all projects")
                        {
                            if (Request["search"] != null)
                            {
                                Debug.Print("hello********************");
                                ViewBag.projects = Dao.Account.getAllProjectsBySearch(user, Request["search"]);
                            }
                            else
                            {
                                ViewBag.projects = Dao.Account.getAllProjectsByUsername(user);
                            }
                            
                        }
                        else if (Request["filter"] == "your projects")
                        {
                            if (Request["search"] != null)
                            {
                                Debug.Print("hello********************");
                                ViewBag.projects = Dao.Account.getAllOwnedProjectsBySearch(user, Request["search"]);
                            }
                            else
                            {
                                ViewBag.projects = Dao.Account.getAllOwnedProjectsByUsername(user);
                            }
                            
                        }

                        
                    }
                    else
                    {
                        //if you are not allowed to see page.
                        ViewBag.projects = new DataRow[0];
                    }
                }

                ViewBag.isProject = false;
                return View();
            }

            //if a project is selected.
            else
            {
                string role = Dao.Account.getRole(User.Identity.GetUserId(), project);
                ViewBag.role = role;

                //overview
                if (type == null)
                {
                    if (User.Identity.IsAuthenticated)
                    {
                        //checks if the user owns this project.

                        DataRow[] sprints = Dao.Account.getAllSprints(project);
                        ViewBag.sprints = sprints;

                    }
                    ViewBag.type = "overview";
                }
                //sprint. shows the current sprint.
                else if(type == "sprint")
                {
                    //finding the last created sprint.
                    DataRow[] rows = Dao.Account.getCurrentSprint(project);
                    //checks if the project has any sprints.
                    if (rows.Length == 0)
                    {
                        //html will show button to create a sprint.
                        ViewBag.sprintExists = false;
                    }
                    else
                    {
                        ViewBag.sprintExists = true;
                        ViewBag.sprint = rows[0];

                        string sprintId = rows[0][0].ToString();

                        DataRow[] tasks = Dao.Account.getTasks(sprintId);
                        ViewBag.tasks = tasks;

                    }

                    ViewBag.type = "sprint";
                }
                //users. shows users for the project.
                else if (type == "users")
                {
                    String user_id = Dao.Account.getUserIdByName(user);
                    String project_id = Dao.Account.getProjectId(user_id, project);
                    DataRow[] users = Dao.Account.getUsers(project_id);
                    ViewBag.users = users;

                    ViewBag.type = "users";
                }

                ViewBag.isProject = true;
                ViewBag.projectName = project;
                ViewBag.userName = user;
                return View();
            }
            
        }

        [Authorize]
        [HttpGet]
        public ActionResult ChangeFilter(string filter, string user)
        {
            
            if (filter == "all projects")
            {
                Debug.Print("asdasdasdasd yes");
                ViewBag.projects = new DataRow[0]; /*Dao.Account.getAllProjectsByUsername(user);*/
            }
            else
            {
                Debug.Print("ddddddddddddd no");
            }

            return Content("");
        }


        [Authorize]
        [HttpPost]
        public ActionResult CreateProject()
        {
            Dao.Account.createProject(User.Identity.GetUserId(), Request["name"], Request["description"]);

            return Content("");
        }


        [Authorize]
        [HttpPost]
        public ActionResult CreateSprint(string name, string start_time, string weeks, string user, string project)
        {
            DateTime time = DateTime.Parse(start_time);
            time = time.AddDays(Double.Parse(weeks) * 7);
            string end_time = time.ToString();


            string role = Dao.Account.getRole(User.Identity.GetUserId(), project);
            if (role == "1")
            {
                string userId = Dao.Account.getUserIdByName(user);
                string projectId = Dao.Account.getProjectId(userId, project);
                Dao.Account.createSprint(projectId, name, start_time, end_time);

                return Content("");
            }
            else
            {
                return Content("");
            }
            
        }

        [Authorize]
        [HttpPost]
        public ActionResult RemoveSprint(string sprint, string project)
        {
            string role = Dao.Account.getRole(User.Identity.GetUserId(), project);
            if (role == "1")
            {
                Dao.Account.removeSprint(sprint);

                return Content("");
            }
            else
            {
                return Content("");
            }

        }

        [Authorize]
        [HttpPost]
        public ActionResult CreateTask(string name, string description, string type, string difficulty, string user, string project, string sprint)
        {
            string role = Dao.Account.getRole(User.Identity.GetUserId(), project);

            if(role == "1" || role == "2")
            {
                Dao.Account.createTask(sprint, name, description, difficulty, type);
            }
            return Content("");
        }

        [Authorize]
        [HttpPost]
        public ActionResult UpdateTaskState(string task, string state, string project)
        {
            string role = Dao.Account.getRole(User.Identity.GetUserId(), project);

            if (role == "1" || role == "2" || role == "3")
            {
                Dao.Account.setTaskState(task, state);
            }
            return Content("");
        }


        [Authorize]
        [HttpPost]
        public ActionResult AddUser(string name, string user_role, string user, string project)
        {
            string role = Dao.Account.getRole(User.Identity.GetUserId(), project);
            
            if (role == "1")
            {
                //user_id is the owner.
                string user_id = Dao.Account.getUserIdByName(user);
                string projectId = Dao.Account.getProjectId(user_id, project);

                //id of the user that will be added
                string userId = Dao.Account.getUserIdByName(name);
                if(userId == null)
                {
                    return Content("{ \"message\": \"Could not find User\", \"success\": false }");
                }
                else if(Dao.Account.UserIsInProject(userId, projectId))
                {
                    return Content("{ \"message\": \"User already exist\" , \"success\": false }");
                }
                else
                {
                    Dao.Account.addUserToProject(userId, user_role, projectId);
                }

                
            }
            return Content("{ \"message\": \"User added to project\" , \"success\": true }");
        }

        [Authorize]
        [HttpPost]
        public ActionResult RemoveUser(string user_id, string project)
        {
            string role = Dao.Account.getRole(User.Identity.GetUserId(), project);
            if (role == "1")
            {
                string projectId = Dao.Account.getProjectId(user_id, project);
                Dao.Account.removeUserFromProject(user_id, projectId);

                return Content("");
            }
            else
            {
                return Content("");
            }

        }


    }
}

TaskManager/Views/Shared/_AddUser.cshtml
<div class="modal fade" id="user_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="exampleModalLabel">Add user</h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <div class="form-group">
                    <label for="name" class="2 col-form-label">Username</label>
                    <input type="text" name="user_name" class="form-control" id="user_name">
                </div>

                <div class="form-group">
                    <label for="exampleFormControlSelect1">Role</label>
                    <select class="form-control" id="user_role">
                        <option value="2">Manager</option>
                        <option value="3">Developer</option>
                    </select>
                </div>

                <input type="hidden" id="sprint_projectName" value="@ViewBag.projectName">
                <input type="hidden" id="sprint_user" value="@ViewBag.userName">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button id="user_create" type="submit" class="btn btn-success">Add user</button>
            </div>
        </div>
    </div>
</div>

TaskManager/Views/Shared/_CreateProject.cshtml
    <div class="modal fade" id="project_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title" id="exampleModalLabel">Create Project</h3>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    <div class="form-group">
                        <label for="name" class="2 col-form-label">Project name</label>
                        <input type="text" name="name" class="form-control" id="name">
                    </div>
                    <div class="form-group">
                        <label for="description" class=" col-form-label">project description</label>
                        <input type="text" name="description" class="form-control" id="description">
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button id="project_create" type="submit" class="btn btn-success" >Create Project</button>
                </div>
            </div>
        </div>
    </div>

TaskManager/Views/Shared/_CreateSprint.cshtml
<div class="modal fade" id="sprint_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="exampleModalLabel">Create Sprint</h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <div class="form-group">
                    <label for="name" class="2 col-form-label">Project name</label>
                    <input type="text" name="sprint_name" class="form-control" id="sprint_name">
                </div>
                <div class="form-group">
                    <label for="start_time" class="2 col-form-label">Start time</label>
                    <input type="date" name="start_time" class="form-control" id="sprint_start_time">
                </div>
                <div class="form-group">
                    <label for="weeks" class="2 col-form-label">weeks</label>
                    <input type="number" name="weeks" class="form-control" id="sprint_weeks">
                </div>
                <input type="hidden" id="sprint_projectName" value="@ViewBag.projectName">
                <input type="hidden" id="sprint_user" value="@ViewBag.userName">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button id="sprint_create" type="submit" class="btn btn-success">Create sprint</button>
            </div>
        </div>
    </div>
</div>

TaskManager/Views/Shared/_CreateTask.cshtml
<div class="modal fade" id="task_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="exampleModalLabel">Create task</h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <div class="form-group">
                    <label for="name" class="2 col-form-label">Title</label>
                    <input type="text" name="task_name" class="form-control" id="task_name">
                </div>
                <div class="form-group">
                    <label for="task_description" class="2 col-form-label">Description</label>
                    <input type="text" name="task_description" class="form-control" id="task_description">
                </div>
                <div class="form-group">
                    <label for="exampleFormControlSelect1">Type</label>
                    <select class="form-control" id="task_type">
                        <option value="1">Issue</option>
                        <option value="2">Feature</option>
                        <option value="3">Investigation</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="exampleFormControlSelect1">difficulty</label>
                    <select class="form-control" id="task_difficulty">
                        <option>1</option>
                        <option>2</option>
                        <option>3</option>
                        <option>4</option>
                        <option>5</option>
                    </select>
                </div>

                <input type="hidden" id="sprint_id" value="@ViewBag.sprint[0]">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button id="task_create" type="submit" class="btn btn-success">Create task</button>
            </div>
        </div>
    </div>
</div>

TaskManager/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Project manager</title>


    
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>


    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Scripts/css/main.css" rel="stylesheet" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark position-fixed fixed-top">
        <a class="navbar-brand" href="#">
            @Html.ActionLink("Project manager", "Index", "ProjectManager", new { area = "" }, new { @class = "navbar-brand" })
        </a>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#nav" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse collapse" id="nav" style="">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">

                    @if (User.Identity.IsAuthenticated)
                    {
                        @Html.ActionLink("My projects", "Users", "ProjectManager", new { user = ViewBag.username, project = "" }, new { @class = "nav-link" })
                    }
                    else
                    {
                        @Html.ActionLink("My projects", "Users", "ProjectManager", new { user = "not logged in" }, new { @class = "nav-link" })
                    }
                </li>

            </ul>
            @Html.Partial("_LoginPartial")

        </div>
    </nav>


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            
        </footer>
    </div>

    <script src="https://getbootstrap.com/docs/4.1/assets/js/vendor/popper.min.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TaskManager/Views/Shared/_RemoveSprint.cshtml
<div class="modal fade" id="sprint_remove_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="exampleModalLabel">Remove Sprint</h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input type="hidden" id="sprint_id" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button id="sprint_remove" type="submit" class="btn btn-danger">Remove sprint</button>
            </div>
        </div>
    </div>
</div>

TaskManager/Views/Shared/_RemoveUser.cshtml
<div class="modal fade" id="user_remove_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="exampleModalLabel">Remove User</h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input type="hidden" id="user_id" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button id="user_remove" type="submit" class="btn btn-danger">Remove User</button>
            </div>
        </div>
    </div>
</div>